# -*- coding: utf-8 -*-
"""AI MODEL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltwctnayxOo8_vDM9L-S4fsOEVm6HsUN

##USING RANDOM FOREST CLASSIFIER
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,mean_squared_error,mean_absolute_error,r2_score

from google.colab import files
uploaded=files.upload()

df=pd.read_csv(r'healthcare-dataset-stroke-data.csv')

df

df.dropna(inplace=True)

x=df[['age','hypertension','heart_disease','avg_glucose_level','bmi']]

x

y=df[['stroke']]

y

grouped = df.groupby('heart_disease')['stroke'].mean().reset_index()
plt.figure(figsize=(10,5))
plt.bar(grouped['heart_disease'], grouped['stroke'])
plt.title("Average stroke for Each heart_disease")
plt.xlabel("heart_disease")
plt.ylabel("Average stroke")
plt.xticks(rotation=45)
plt.show()

grouped = df.groupby('age')['stroke'].mean().reset_index()
plt.figure(figsize=(8,5))
plt.scatter(grouped['age'], grouped['stroke'])
plt.title("age vs stroke")
plt.xlabel("age")
plt.ylabel("Average stroke")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

grouped = df.groupby('bmi')['stroke'].mean().reset_index()
plt.plot(grouped['bmi'], grouped['stroke'])
plt.title("bmi vs Average stroke")
plt.xlabel("bmi")
plt.ylabel("Average stroke")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

smoking_status = df['smoking_status'].value_counts()
plt.title("smoking status")
plt.pie(smoking_status, labels=smoking_status.index, autopct='%1.1f%%',startangle=90)
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df['hypertension'], bins=10, alpha=0.5, label='hypertension', color='darkblue')
plt.hist(df['stroke'], bins=10, alpha=0.5, label='stroke', color='yellow')
plt.hist(df['smoking_status'], bins=10, alpha=0.5, label='smoking_status', color='salmon')
plt.xlabel("predictions")
plt.ylabel("Frequency")
plt.title("Distribution of hypertension, stroke, and smoking_status")
plt.legend()
plt.show()

import matplotlib.pyplot as plt
grouped = df.groupby('heart_disease')['stroke'].mean().reset_index()
gender_grouped = df.groupby('age').size()
plt.figure(figsize=(14,10))

# Bar Chart
plt.subplot(2,3,1)
plt.bar(grouped['heart_disease'], grouped['stroke'])
plt.xlabel("heart_disease")
plt.ylabel("stroke")

# Scatter Chart
plt.subplot(2,3,2)
plt.scatter(grouped['heart_disease'], grouped['stroke'])
plt.xlabel("heart_disease")
plt.ylabel("stroke")

# Line Chart
plt.subplot(2,3,3)
plt.plot(grouped['heart_disease'], grouped['stroke'])
plt.xlabel("heart_disease")
plt.ylabel("stroke")

# Pie Chart
plt.subplot(2,3,4)
plt.pie(
    smoking_status,
    labels=smoking_status.index,
    autopct='%1.1f%%',
    startangle=90
)

# Histogram
plt.subplot(2,3,5)
plt.hist(df['hypertension'], bins=10)
plt.xlabel("hypertension")
plt.ylabel("Frequency")

# Histogram
plt.subplot(2,3,6)
plt.hist(df['stroke'], bins=10)
plt.xlabel("stroke")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

x_train

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()

model = RandomForestClassifier()

model.fit(x_train, y_train)

y_predict=model.predict(x_test)

mse=mean_squared_error(y_test,y_predict)
mae=mean_absolute_error(y_test,y_predict)
r2=r2_score(y_test,y_predict)
print("Mean Absolute Error:",mae)
print("Mean Squared Error:",mse)
print("R-squared:",r2)
print('Accuracy Score:', accuracy_score(y_test, y_predict))

import seaborn as sns

cm=confusion_matrix(y_test,y_predict)

sns.heatmap(cm,annot=True)